from __future__ import annotations


def _terms(value: str) -> list[str]:
    return [line.strip() for line in value.strip().splitlines() if line.strip()]


HRS1_P = _terms(r'''
"Surgical Procedures, Operative"[Mesh]
"Perioperative Care"[Mesh]
"Perioperative Period"[Mesh]
"Preoperative Care"[Mesh]
"Intraoperative Care"[Mesh]
"Postoperative Care"[Mesh]
"Ambulatory Surgical Procedures"[Mesh]
"Elective Surgical Procedures"[Mesh]
"Minimally Invasive Surgical Procedures"[Mesh]
"Minor Surgical Procedures"[Mesh]
"Endoscopy"[Mesh]
"Biopsy"[Mesh]
"Catheterization"[Mesh]
"Anesthesia"[Mesh]
perioperativ*[tiab]
preoperativ*[tiab]
intraoperativ*[tiab]
postoperativ*[tiab]
peroperative[tiab]
periprocedural[tiab]
"peri-procedural"[tiab]
preprocedural[tiab]
"pre-procedural"[tiab]
intraprocedural[tiab]
"intra-procedural"[tiab]
postprocedural[tiab]
"post-procedural"[tiab]
surgery[tiab]
surgic*[tiab]
operation[tiab]
operative[tiab]
"operative procedure"[tiab]
"operative procedures"[tiab]
"surgical procedure"[tiab]
"surgical procedures"[tiab]
"surgical intervention"[tiab]
"surgical interventions"[tiab]
"invasive procedure"[tiab]
"invasive procedures"[tiab]
"invasive intervention"[tiab]
"invasive interventions"[tiab]
anesthesia[tiab]
anaesthesia[tiab]
anesthetic[tiab]
anaesthetic[tiab]
preanesthetic[tiab]
preanaesthetic[tiab]
"operating room"[tiab]
"operating theater"[tiab]
"operating theatre"[tiab]
"day surgery"[tiab]
"day-case surgery"[tiab]
"ambulatory surgery"[tiab]
"outpatient surgery"[tiab]
"elective surgery"[tiab]
"emergency surgery"[tiab]
"minor surgery"[tiab]
"major surgery"[tiab]
"minimally invasive surgery"[tiab]
endoscop*[tiab]
biops*[tiab]
catheteriz*[tiab]
catheteris*[tiab]
cesarean[tiab]
caesarean[tiab]
"orthopedic surgery"[tiab]
"orthopaedic surgery"[tiab]
ERAS[tiab]
"enhanced recovery after surgery"[tiab]
''')

HRS1_I = _terms(r'''
"Dietary Supplements"[Mesh]
"Phytotherapy"[Mesh]
"Plant Preparations"[Mesh]
"Plants, Medicinal"[Mesh]
"Plant Extracts"[Mesh]
"Herbal Medicine"[Mesh]
"Medicine, Traditional"[Mesh]
"Medicine, Chinese Traditional"[Mesh]
"Medicine, Kampo"[Mesh]
"Drugs, Chinese Herbal"[Mesh]
"Complementary Therapies"[Mesh]
"Vitamins"[Mesh]
"Micronutrients"[Mesh]
"Trace Elements"[Mesh]
"Fish Oils"[Mesh]
"Fatty Acids, Omega-3"[Mesh]
"Vitamin E"[Mesh]
"dietary supplement*"[tiab]
"dietary supplementation"[tiab]
"food supplement*"[tiab]
"food supplementation"[tiab]
"nutritional supplement*"[tiab]
"nutrient supplement*"[tiab]
"vitamin supplement*"[tiab]
"mineral supplement*"[tiab]
"micronutrient supplement*"[tiab]
"herbal supplement*"[tiab]
"botanical supplement*"[tiab]
"herbal medicine*"[tiab]
"herbal remedy"[tiab]
"herbal remedies"[tiab]
"herbal preparation*"[tiab]
"plant preparation*"[tiab]
"plant extract*"[tiab]
phytothera*[tiab]
phytomedicin*[tiab]
"complementary medicine"[tiab]
"alternative medicine"[tiab]
"complementary and alternative medicine"[tiab]
"traditional medicine"[tiab]
"traditional Chinese medicine"[tiab]
TCM[tiab]
Ayurveda[tiab]
Ayurvedic[tiab]
Kampo[tiab]
nutraceutic*[tiab]
nutriceutic*[tiab]
neutraceutic*[tiab]
multivitamin*[tiab]
ginkgo[tiab]
"ginkgo biloba"[tiab]
"EGb 761"[tiab]
Tebonin[tiab]
garlic[tiab]
"Allium sativum"[tiab]
"aged garlic extract"[tiab]
Kyolic[tiab]
ginseng[tiab]
"Panax ginseng"[tiab]
Ginsana[tiab]
"St John's wort"[tiab]
"Hypericum perforatum"[tiab]
"LI 160"[tiab]
"WS 5570"[tiab]
kava[tiab]
"Piper methysticum"[tiab]
valerian[tiab]
"Valeriana officinalis"[tiab]
echinacea[tiab]
"Echinacea purpurea"[tiab]
ephedra[tiab]
"ma huang"[tiab]
ginger[tiab]
"Zingiber officinale"[tiab]
turmeric[tiab]
"Curcuma longa"[tiab]
curcumin[tiab]
"fish oil"[tiab]
"omega-3"[tiab]
EPA[tiab]
DHA[tiab]
Omacor[tiab]
Lovaza[tiab]
"vitamin E"[tiab]
"alpha-tocopherol"[tiab]
tocopherol*[tiab]
"saw palmetto"[tiab]
"Serenoa repens"[tiab]
"coenzyme Q10"[tiab]
CoQ10[tiab]
Pycnogenol[tiab]
ashwagandha[tiab]
"Withania somnifera"[tiab]
"KSM-66"[tiab]
Sensoril[tiab]
''')

HRS2_P = _terms(r'''
"Renal Insufficiency, Chronic"[Mesh]
"Kidney Failure, Chronic"[Mesh]
"Renal Dialysis"[Mesh]
"Peritoneal Dialysis"[Mesh]
"Uremia"[Mesh]
"Diabetic Nephropathies"[Mesh]
"Chronic Kidney Disease-Mineral and Bone Disorder"[Mesh]
"chronic kidney disease"[tiab]
"chronic renal disease"[tiab]
"chronic kidney insufficiency"[tiab]
"chronic renal insufficiency"[tiab]
"chronic kidney failure"[tiab]
"chronic renal failure"[tiab]
"chronic kidney impairment"[tiab]
"chronic renal impairment"[tiab]
"end stage kidney disease"[tiab]
"end-stage kidney disease"[tiab]
"end stage renal disease"[tiab]
"end-stage renal disease"[tiab]
"end stage kidney failure"[tiab]
"end-stage kidney failure"[tiab]
"end stage renal failure"[tiab]
"end-stage renal failure"[tiab]
CKD[tiab]
ESKD[tiab]
ESRD[tiab]
"CKD stage 3"[tiab]
"CKD stage 4"[tiab]
"CKD stage 5"[tiab]
"stage 3 chronic kidney disease"[tiab]
"stage 4 chronic kidney disease"[tiab]
"stage 5 chronic kidney disease"[tiab]
predialysis[tiab]
"pre-dialysis"[tiab]
"nondialysis dependent"[tiab]
"non-dialysis-dependent"[tiab]
"dialysis dependent"[tiab]
"dialysis-dependent"[tiab]
dialys*[tiab]
dialyz*[tiab]
hemodialys*[tiab]
haemodialys*[tiab]
"peritoneal dialys*"[tiab]
"continuous ambulatory peritoneal dialysis"[tiab]
"automated peritoneal dialysis"[tiab]
"continuous cycling peritoneal dialysis"[tiab]
"maintenance hemodialysis"[tiab]
"maintenance haemodialysis"[tiab]
CAPD[tiab]
CCPD[tiab]
uremi*[tiab]
uraemi*[tiab]
"CKD-MBD"[tiab]
"NxStage System One"[tiab]
"Tablo Hemodialysis System"[tiab]
"HomeChoice Claria"[tiab]
''')

HRS2_I = _terms(r'''
"Dietary Supplements"[Mesh]
"Herbal Medicine"[Mesh]
"Phytotherapy"[Mesh]
"Plants, Medicinal"[Mesh]
"Plant Extracts"[Mesh]
"Vitamins"[Mesh]
"Micronutrients"[Mesh]
"Minerals"[Mesh]
"Trace Elements"[Mesh]
"Ascorbic Acid"[Mesh]
"Vitamin D"[Mesh]
"Calcium"[Mesh]
"Magnesium"[Mesh]
"Panax"[Mesh]
"Ginkgo biloba"[Mesh]
"Garlic"[Mesh]
"Curcumin"[Mesh]
"Hypericum"[Mesh]
"Glycyrrhiza"[Mesh]
"dietary supplement*"[tiab]
"dietary supplementation"[tiab]
"food supplement*"[tiab]
"nutritional supplement*"[tiab]
"nutrition supplement*"[tiab]
nutraceutic*[tiab]
"vitamin supplement*"[tiab]
multivitamin*[tiab]
multi-vitamin*[tiab]
"vitamin-mineral supplement*"[tiab]
"multivitamin-mineral supplement*"[tiab]
"mineral supplement*"[tiab]
multimineral*[tiab]
multi-mineral*[tiab]
"trace element supplement*"[tiab]
"micronutrient supplement*"[tiab]
"herbal supplement*"[tiab]
"herb supplement*"[tiab]
"herbal and dietary supplement*"[tiab]
"botanical supplement*"[tiab]
"plant-based supplement*"[tiab]
"plant derived supplement*"[tiab]
phytotherap*[tiab]
phytomedicin*[tiab]
"herbal medic*"[tiab]
"herbal remed*"[tiab]
"herbal preparation*"[tiab]
"plant extract*"[tiab]
"botanical product*"[tiab]
"traditional Chinese medicine"[tiab]
"Chinese herbal medic*"[tiab]
"traditional herbal medicine"[tiab]
"natural health product*"[tiab]
"over-the-counter supplement*"[tiab]
"OTC supplement*"[tiab]
"nonprescription supplement*"[tiab]
"non-prescription supplement*"[tiab]
"vitamin preparation*"[tiab]
"mineral preparation*"[tiab]
"food adjunct*"[tiab]
"dietetic preparation*"[tiab]
"health food supplement*"[tiab]
"orthomolecular medicine"[tiab]
HDS[tiab]
MVM[tiab]
MVI[tiab]
CHM[tiab]
"Nephro-Vite"[tiab]
Nephrovite[tiab]
Centrum[tiab]
"vitamin A"[tiab]
retinol[tiab]
"vitamin C"[tiab]
"ascorbic acid"[tiab]
ascorbate[tiab]
"vitamin D"[tiab]
cholecalciferol[tiab]
ergocalciferol[tiab]
"vitamin E"[tiab]
"folic acid"[tiab]
folate*[tiab]
"calcium supplement*"[tiab]
"magnesium supplement*"[tiab]
"potassium supplement*"[tiab]
"iron supplement*"[tiab]
"zinc supplement*"[tiab]
"selenium supplement*"[tiab]
ginseng[tiab]
"Panax ginseng"[tiab]
ginkgo[tiab]
"Ginkgo biloba"[tiab]
garlic[tiab]
"Allium sativum"[tiab]
turmeric[tiab]
curcumin[tiab]
"Curcuma longa"[tiab]
"St John's wort"[tiab]
"St Johns wort"[tiab]
"Hypericum perforatum"[tiab]
echinacea[tiab]
"milk thistle"[tiab]
silymarin[tiab]
licorice[tiab]
liquorice[tiab]
glycyrrhiza[tiab]
astragalus[tiab]
"Astragalus membranaceus"[tiab]
aristolochia[tiab]
"aristolochic acid"[tiab]
''')

HRS3_P = _terms(r'''
"Pregnancy"[Mesh]
"Pregnant People"[Mesh]
"Pregnancy Trimesters"[Mesh]
"Pregnancy Trimester, First"[Mesh]
"Pregnancy Trimester, Second"[Mesh]
"Pregnancy Trimester, Third"[Mesh]
"Pregnancy, High-Risk"[Mesh]
"Gravidity"[Mesh]
"Fetus"[Mesh]
"Infant, Newborn"[Mesh]
"Prenatal Care"[Mesh]
"Maternal-Fetal Relations"[Mesh]
"Maternal Exposure"[Mesh]
"Embryonic and Fetal Development"[Mesh]
pregnan*[tiab]
gestation*[tiab]
gravidity[tiab]
gravida*[tiab]
gravid[tiab]
parturient*[tiab]
"pregnant woman"[tiab]
"pregnant women"[tiab]
"pregnant person"[tiab]
"pregnant people"[tiab]
"expectant mother*"[tiab]
antenatal[tiab]
ante-natal[tiab]
prenatal[tiab]
pre-natal[tiab]
perinatal[tiab]
peri-natal[tiab]
maternal[tiab]
maternity[tiab]
"maternal-fetal"[tiab]
"maternal-foetal"[tiab]
fetus[tiab]
fetuses[tiab]
foetus[tiab]
foetuses[tiab]
fetal[tiab]
foetal[tiab]
neonat*[tiab]
newborn*[tiab]
"new born"[tiab]
"in utero"[tiab]
intrauterine[tiab]
intra-uterine[tiab]
embryo*[tiab]
conceptus[tiab]
obstetric*[tiab]
trimester*[tiab]
"gestational age"[tiab]
"gestational age (GA)"[tiab]
''')

HRS3_I = _terms(r'''
"Dietary Supplements"[Mesh]
"Phytotherapy"[Mesh]
"Plant Preparations"[Mesh]
"Herbal Medicine"[Mesh]
"Drugs, Chinese Herbal"[Mesh]
"Vitamins"[Mesh]
"Minerals"[Mesh]
"Trace Elements"[Mesh]
"Micronutrients"[Mesh]
"Folic Acid"[Mesh]
"Iron"[Mesh]
"Vitamin D"[Mesh]
"Calcium"[Mesh]
"Iodine"[Mesh]
"Fatty Acids, Omega-3"[Mesh]
"Fish Oils"[Mesh]
"Probiotics"[Mesh]
"Choline"[Mesh]
"dietary supplement*"[tiab]
"food supplement*"[tiab]
"nutritional supplement*"[tiab]
"nutrition supplement*"[tiab]
nutraceutical*[tiab]
"herbal supplement*"[tiab]
"botanical supplement*"[tiab]
"plant-based supplement*"[tiab]
"plant based supplement*"[tiab]
phytotherap*[tiab]
"herbal medicine*"[tiab]
"herbal remed*"[tiab]
"medicinal herb*"[tiab]
"traditional herbal medicine*"[tiab]
"vitamin supplement*"[tiab]
"mineral supplement*"[tiab]
"micronutrient supplement*"[tiab]
multivitamin*[tiab]
multimineral*[tiab]
"prenatal vitamin*"[tiab]
"prenatal multivitamin*"[tiab]
"prenatal supplement*"[tiab]
"antenatal supplement*"[tiab]
"maternal supplement*"[tiab]
"pregnancy supplement*"[tiab]
"multiple micronutrient supplement*"[tiab]
"multiple micronutrient supplementation"[tiab]
MMN[tiab]
MMS[tiab]
MVM[tiab]
PNV[tiab]
"materia medica"[tiab]
galenical*[tiab]
"botanic drug*"[tiab]
"vitamin preparation*"[tiab]
"folic acid"[tiab]
folate*[tiab]
methylfolate[tiab]
5-MTHF[tiab]
"folinic acid"[tiab]
"iron supplement*"[tiab]
"ferrous sulfate"[tiab]
"ferrous sulphate"[tiab]
"ferrous fumarate"[tiab]
"ferrous gluconate"[tiab]
"vitamin D"[tiab]
cholecalciferol[tiab]
ergocalciferol[tiab]
"calcium supplement*"[tiab]
"calcium carbonate"[tiab]
"calcium citrate"[tiab]
iodine[tiab]
iodide[tiab]
"potassium iodide"[tiab]
"vitamin A"[tiab]
retinol[tiab]
beta-carotene[tiab]
"beta carotene"[tiab]
"vitamin B12"[tiab]
cyanocobalamin[tiab]
"vitamin B6"[tiab]
pyridoxine[tiab]
"vitamin C"[tiab]
"ascorbic acid"[tiab]
"zinc supplement*"[tiab]
"selenium supplement*"[tiab]
"magnesium supplement*"[tiab]
"choline supplement*"[tiab]
myo-inositol[tiab]
omega-3[tiab]
"omega 3"[tiab]
"n-3 fatty acid*"[tiab]
"fish oil*"[tiab]
"docosahexaenoic acid*"[tiab]
DHA[tiab]
probiotic*[tiab]
ginger[tiab]
"Zingiber officinale"[tiab]
ginseng[tiab]
Panax[tiab]
echinacea[tiab]
"Echinacea purpurea"[tiab]
turmeric[tiab]
curcumin[tiab]
"evening primrose"[tiab]
"Oenothera biennis"[tiab]
"raspberry leaf"[tiab]
"Rubus idaeus"[tiab]
"St John's wort"[tiab]
"St. John's wort"[tiab]
"Hypericum perforatum"[tiab]
garlic[tiab]
"Allium sativum"[tiab]
cranberry[tiab]
"Vaccinium macrocarpon"[tiab]
"black cohosh"[tiab]
"Actaea racemosa"[tiab]
"Cimicifuga racemosa"[tiab]
"blue cohosh"[tiab]
"Caulophyllum thalictroides"[tiab]
Elevit[tiab]
Pregnacare[tiab]
PregVit[tiab]
''')

HRS4_P = _terms(r'''
"Liver Diseases"[Mesh]
"Liver Cirrhosis"[Mesh]
"Hepatitis, Chronic"[Mesh]
"Hepatitis B, Chronic"[Mesh]
"Hepatitis C, Chronic"[Mesh]
"Hepatitis, Autoimmune"[Mesh]
"Non-alcoholic Fatty Liver Disease"[Mesh]
"Liver Diseases, Alcoholic"[Mesh]
"Liver Cirrhosis, Biliary"[Mesh]
"Cholangitis, Sclerosing"[Mesh]
"Hepatolenticular Degeneration"[Mesh]
"Hemochromatosis"[Mesh]
"Hypertension, Portal"[Mesh]
"Fatty Liver"[Mesh]
"liver disease*"[tiab]
"hepatic disease*"[tiab]
"chronic liver disease*"[tiab]
"chronic hepatic disease*"[tiab]
"preexisting liver disease*"[tiab]
"pre-existing liver disease*"[tiab]
"underlying liver disease*"[tiab]
hepatopath*[tiab]
cirrhos*[tiab]
cirrhot*[tiab]
"liver fibros*"[tiab]
"hepatic fibros*"[tiab]
"chronic hepatitis"[tiab]
"hepatitis B"[tiab]
"hepatitis C"[tiab]
HBV[tiab]
HCV[tiab]
"alcoholic liver disease"[tiab]
"alcohol-related liver disease"[tiab]
"alcohol-associated liver disease"[tiab]
ALD[tiab]
"steatotic liver disease"[tiab]
"metabolic dysfunction-associated steatotic liver disease"[tiab]
MASLD[tiab]
"metabolic dysfunction-associated steatohepatitis"[tiab]
MASH[tiab]
"metabolic associated fatty liver disease"[tiab]
MAFLD[tiab]
"nonalcoholic fatty liver disease"[tiab]
"non-alcoholic fatty liver disease"[tiab]
NAFLD[tiab]
"nonalcoholic steatohepatitis"[tiab]
NASH[tiab]
"hepatic steatosis"[tiab]
"autoimmune hepatitis"[tiab]
"primary biliary cholangitis"[tiab]
"primary biliary cirrhosis"[tiab]
PBC[tiab]
"primary sclerosing cholangitis"[tiab]
PSC[tiab]
"portal hypertension"[tiab]
"Wilson disease"[tiab]
hemochromatosis[tiab]
haemochromatosis[tiab]
"advanced liver disease*"[tiab]
"end-stage liver disease*"[tiab]
ESLD[tiab]
"postnecrotic cirrhosis"[tiab]
"Laennec's cirrhosis"[tiab]
"cryptogenic cirrhosis"[tiab]
"decompensated cirrhosis"[tiab]
''')

HRS4_I = _terms(r'''
"Dietary Supplements"[Mesh]
"Phytotherapy"[Mesh]
"Plant Extracts"[Mesh]
"Plants, Medicinal"[Mesh]
"Drugs, Chinese Herbal"[Mesh]
"Vitamins"[Mesh]
"Micronutrients"[Mesh]
"Trace Elements"[Mesh]
"Probiotics"[Mesh]
"Prebiotics"[Mesh]
"Synbiotics"[Mesh]
"Teas, Herbal"[Mesh]
"dietary supplement*"[tiab]
"food supplement*"[tiab]
"nutritional supplement*"[tiab]
"nutrition supplement*"[tiab]
"vitamin supplement*"[tiab]
"mineral supplement*"[tiab]
"micronutrient supplement*"[tiab]
multivitamin*[tiab]
multi-vitamin*[tiab]
multimineral*[tiab]
multi-mineral*[tiab]
nutraceutic*[tiab]
neutraceutic*[tiab]
"dietary supplementation"[tiab]
"nutrient supplementation"[tiab]
"herbal supplement*"[tiab]
"herb supplement*"[tiab]
"botanical supplement*"[tiab]
"plant-based supplement*"[tiab]
"herbal medicine*"[tiab]
"herbal medicinal product*"[tiab]
"herbal remedy"[tiab]
"herbal remedies"[tiab]
"traditional herbal medicine*"[tiab]
"Chinese herbal medicine*"[tiab]
"traditional Chinese medicine"[tiab]
TCM[tiab]
Kampo[tiab]
Ayurved*[tiab]
phytotherap*[tiab]
phytomedicin*[tiab]
"plant extract"[tiab]
"plant extracts"[tiab]
"medicinal plant"[tiab]
"medicinal plants"[tiab]
"botanical extract"[tiab]
"botanical extracts"[tiab]
"natural health product"[tiab]
"natural health products"[tiab]
HDS[tiab]
"herbal and dietary supplement*"[tiab]
"multi-ingredient supplement*"[tiab]
"bodybuilding supplement*"[tiab]
"weight loss supplement*"[tiab]
"sports supplement*"[tiab]
"performance-enhancing supplement*"[tiab]
"health food*"[tiab]
"fiber supplement*"[tiab]
"fibre supplement*"[tiab]
"standardized herbal extract*"[tiab]
"standardised herbal extract*"[tiab]
silymarin[tiab]
"milk thistle"[tiab]
"Silybum marianum"[tiab]
turmeric[tiab]
curcumin[tiab]
"Curcuma longa"[tiab]
"green tea extract"[tiab]
EGCG[tiab]
"Camellia sinensis"[tiab]
ashwagandha[tiab]
"Withania somnifera"[tiab]
"black cohosh"[tiab]
"Actaea racemosa"[tiab]
"Cimicifuga racemosa"[tiab]
kava[tiab]
"Piper methysticum"[tiab]
kratom[tiab]
"Mitragyna speciosa"[tiab]
"Garcinia cambogia"[tiab]
"red yeast rice"[tiab]
ephedra[tiab]
"ma huang"[tiab]
"usnic acid"[tiab]
licorice[tiab]
liquorice[tiab]
"Glycyrrhiza glabra"[tiab]
"vitamin A"[tiab]
retinol[tiab]
niacin[tiab]
Herbalife[tiab]
Hydroxycut[tiab]
"OxyELITE Pro"[tiab]
LipoKinetix[tiab]
''')

HRS5_P = _terms(r'''
"Anticoagulants"[Mesh]
"4-Hydroxycoumarins"[Mesh]
"Warfarin"[Mesh]
"Heparin"[Mesh]
"Heparin, Low-Molecular-Weight"[Mesh]
"Factor Xa Inhibitors"[Mesh]
"Antithrombins"[Mesh]
"Dabigatran"[Mesh]
"Rivaroxaban"[Mesh]
"Heparinoids"[Mesh]
anticoagulant*[tiab]
anticoagulation[tiab]
"oral anticoagulant*"[tiab]
"oral anticoagulation"[tiab]
OAC[tiab]
OACs[tiab]
"vitamin K antagonist*"[tiab]
VKA[tiab]
VKAs[tiab]
"coumarin anticoagulant*"[tiab]
"4-hydroxycoumarin*"[tiab]
"direct oral anticoagulant*"[tiab]
"direct-acting oral anticoagulant*"[tiab]
"direct acting oral anticoagulant*"[tiab]
DOAC[tiab]
DOACs[tiab]
"non-vitamin K antagonist oral anticoagulant*"[tiab]
"nonvitamin K antagonist oral anticoagulant*"[tiab]
"novel oral anticoagulant*"[tiab]
"new oral anticoagulant*"[tiab]
NOAC[tiab]
NOACs[tiab]
"factor Xa inhibitor*"[tiab]
"factor 10a inhibitor*"[tiab]
"FXa inhibitor*"[tiab]
"direct thrombin inhibitor*"[tiab]
"blood thinner*"[tiab]
"unfractionated heparin"[tiab]
UFH[tiab]
"low molecular weight heparin*"[tiab]
"low-molecular-weight heparin*"[tiab]
LMWH[tiab]
heparin[tiab]
heparinoid*[tiab]
warfarin[tiab]
"warfarin sodium"[tiab]
Coumadin[tiab]
Jantoven[tiab]
acenocoumarol[tiab]
nicoumalone[tiab]
Sintrom[tiab]
Sinthrome[tiab]
phenprocoumon[tiab]
Marcumar[tiab]
fluindione[tiab]
Previscan[tiab]
phenindione[tiab]
dicumarol[tiab]
dicoumarol[tiab]
apixaban[tiab]
Eliquis[tiab]
"BMS 562247"[tiab]
rivaroxaban[tiab]
Xarelto[tiab]
"BAY 59-7939"[tiab]
edoxaban[tiab]
Savaysa[tiab]
Lixiana[tiab]
"DU 176b"[tiab]
dabigatran[tiab]
"dabigatran etexilate"[tiab]
Pradaxa[tiab]
"BIBR 1048"[tiab]
betrixaban[tiab]
Bevyxxa[tiab]
ximelagatran[tiab]
Exanta[tiab]
enoxaparin[tiab]
Lovenox[tiab]
Clexane[tiab]
dalteparin[tiab]
Fragmin[tiab]
tinzaparin[tiab]
Innohep[tiab]
nadroparin[tiab]
Fraxiparine[tiab]
bemiparin[tiab]
Hibor[tiab]
certoparin[tiab]
"Mono-Embolex"[tiab]
''')

HRS5_I = _terms(r'''
"Dietary Supplements"[Mesh]
"Phytotherapy"[Mesh]
"Plant Preparations"[Mesh]
"Plants, Medicinal"[Mesh]
"Vitamins"[Mesh]
"Minerals"[Mesh]
"Trace Elements"[Mesh]
"Fish Oils"[Mesh]
"Fatty Acids, Omega-3"[Mesh]
"Vitamin E"[Mesh]
"Vitamin K"[Mesh]
"Ubiquinone"[Mesh]
"Ginkgo biloba"[Mesh]
"Panax"[Mesh]
"Garlic"[Mesh]
"Curcumin"[Mesh]
"Hypericum"[Mesh]
"Camellia sinensis"[Mesh]
"Zingiber officinale"[Mesh]
"Angelica sinensis"[Mesh]
"Salvia miltiorrhiza"[Mesh]
"Vaccinium macrocarpon"[Mesh]
"dietary supplement*"[tiab]
"dietary supplementation"[tiab]
"food supplement*"[tiab]
"nutritional supplement*"[tiab]
"nutrition supplement*"[tiab]
"micronutrient supplement*"[tiab]
"vitamin supplement*"[tiab]
"mineral supplement*"[tiab]
"herbal supplement*"[tiab]
"herb supplement*"[tiab]
"botanical supplement*"[tiab]
"plant-based supplement*"[tiab]
"plant based supplement*"[tiab]
"herbal medicine*"[tiab]
"herbal medicinal product*"[tiab]
"herbal remed*"[tiab]
"plant preparation*"[tiab]
"plant extract*"[tiab]
"botanical product*"[tiab]
botanical*[tiab]
phytotherap*[tiab]
phytomedicine*[tiab]
phytopharmaceutical*[tiab]
nutraceutical*[tiab]
nutriceutical*[tiab]
neutraceutical*[tiab]
"natural health product*"[tiab]
NHP[tiab]
NHPs[tiab]
"herbal and dietary supplement*"[tiab]
"dietary and herbal supplement*"[tiab]
HDS[tiab]
DHS[tiab]
"OTC supplement*"[tiab]
"over-the-counter supplement*"[tiab]
"nonprescription supplement*"[tiab]
"non-prescription supplement*"[tiab]
"health food*"[tiab]
galenical*[tiab]
"herbal tonic*"[tiab]
"dietary fibre supplement*"[tiab]
"dietary fiber supplement*"[tiab]
"standardised herbal extract*"[tiab]
"standardized herbal extract*"[tiab]
multivitamin*[tiab]
"multivitamin multimineral*"[tiab]
MVM[tiab]
Centrum[tiab]
Kyolic[tiab]
Tebonin[tiab]
"EGb 761"[tiab]
G115[tiab]
Metamucil[tiab]
ginkgo[tiab]
"Ginkgo biloba"[tiab]
ginseng[tiab]
"Panax ginseng"[tiab]
"Panax quinquefolius"[tiab]
garlic[tiab]
"Allium sativum"[tiab]
ginger[tiab]
"Zingiber officinale"[tiab]
turmeric[tiab]
curcumin[tiab]
"St John's wort"[tiab]
"Saint John's wort"[tiab]
hypericum[tiab]
"Hypericum perforatum"[tiab]
cranberry[tiab]
"Vaccinium macrocarpon"[tiab]
"green tea"[tiab]
"Camellia sinensis"[tiab]
"fish oil*"[tiab]
"omega-3"[tiab]
"omega 3"[tiab]
"omega-3 fatty acid*"[tiab]
"omega 3 fatty acid*"[tiab]
"vitamin E"[tiab]
tocopherol*[tiab]
"vitamin K"[tiab]
phylloquinone[tiab]
menaquinone*[tiab]
"coenzyme Q10"[tiab]
CoQ10[tiab]
ubiquinone[tiab]
ubidecarenone[tiab]
glucosamine[tiab]
chondroitin[tiab]
feverfew[tiab]
"Tanacetum parthenium"[tiab]
"dong quai"[tiab]
"Angelica sinensis"[tiab]
danshen[tiab]
"Salvia miltiorrhiza"[tiab]
licorice[tiab]
liquorice[tiab]
glycyrrhiza[tiab]
"saw palmetto"[tiab]
"Serenoa repens"[tiab]
"red clover"[tiab]
"Trifolium pratense"[tiab]
"evening primrose"[tiab]
"Oenothera biennis"[tiab]
"grape seed*"[tiab]
"Vitis vinifera"[tiab]
resveratrol[tiab]
quercetin[tiab]
bromelain[tiab]
chamomile[tiab]
"Matricaria chamomilla"[tiab]
cinnamon[tiab]
"Cinnamomum cassia"[tiab]
nattokinase[tiab]
natto[tiab]
''')


QUESTION_SPECS = {
    "HRS1_PERIOPERATIVE": {
        "question": "수술 또는 침습적 시술을 받는 성인에서 수술 전 식이·허브 보충제 노출은 비노출 또는 통상 관리와 비교해 출혈, 수혈, 마취 상호작용 또는 수술주위 합병증과 관련되는가?",
        "p_terms": HRS1_P,
        "i_terms": HRS1_I,
    },
    "HRS2_KIDNEY_DISEASE": {
        "question": "만성콩팥병 또는 투석 환자에서 비처방 비타민·무기질·허브 보충제 노출은 비노출 또는 통상 관리와 비교해 전해질 이상, 신독성 또는 심혈관 이상반응과 관련되는가?",
        "p_terms": HRS2_P,
        "i_terms": HRS2_I,
    },
    "HRS3_PREGNANCY": {
        "question": "임신 중 식이·허브 보충제 노출은 비노출 또는 통상 산전관리와 비교해 산모 독성, 임신 합병증, 태아 이상 또는 신생아 이상반응과 관련되는가?",
        "p_terms": HRS3_P,
        "i_terms": HRS3_I,
    },
    "HRS4_LIVER_DISEASE": {
        "question": "기존 간질환이 있는 환자에서 식이·허브 보충제 노출은 비노출 또는 통상 관리와 비교해 간손상, 간기능 악화 또는 입원과 관련되는가?",
        "p_terms": HRS4_P,
        "i_terms": HRS4_I,
    },
    "HRS5_ANTICOAGULATION": {
        "question": "항응고제를 사용하는 환자에서 식이·허브 보충제 병용은 비병용과 비교해 출혈, 혈전, 응고검사 변화 또는 약물 상호작용과 관련되는가?",
        "p_terms": HRS5_P,
        "i_terms": HRS5_I,
    },
}


TERM_CATEGORY_EVIDENCE = {
    "P": [
        "controlled_vocabulary", "free_text", "general_names", "abbreviations",
        "class_or_subtype_names", "US_UK_spelling_variants", "truncation",
        "legacy_terms", "representative_entities",
    ],
    "I": [
        "controlled_vocabulary", "free_text", "general_names", "product_names",
        "abbreviations", "class_names", "US_UK_spelling_variants", "truncation",
        "legacy_terms", "representative_ingredients",
    ],
}
