"use client";
import { useEffect, useState } from "react";
const KEY = "nutrition-safety-next-step-review-v1";
export function NextStepReviewClient() {
  const [done, setDone] = useState(false);
  useEffect(() => { const timer = setTimeout(() => setDone(localStorage.getItem(KEY) === "approved"), 0); return () => clearTimeout(timer); }, []);
  function approve() { localStorage.setItem(KEY, "approved"); localStorage.setItem(`${KEY}-at`, new Date().toISOString()); setDone(true); }
  function download() { const payload = { schema: "workflow-amendment-approval-v1", decision: "approve_screening_before_study_linkage", approvedAt: localStorage.getItem(`${KEY}-at`) }; const blob = new Blob([JSON.stringify(payload, null, 2)], {type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download="next-step-review-approval.json"; a.click(); URL.revokeObjectURL(a.href); }
  return <main className="min-h-[75vh] bg-[#f9fafb] px-5 py-16 text-[#191f28]"><div className="mx-auto max-w-[820px]"><p className="text-lg font-bold text-[#3182f6]">다음 연구 단계</p><h1 className="mt-3 text-[36px] font-bold leading-tight sm:text-[46px]">다음 순서도 정리했습니다.<br/>한 번만 승인해 주세요.</h1>{done?<section className="mt-10 rounded-[28px] bg-white p-12 text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#e8f8f2] text-4xl font-bold text-[#008c63]">✓</div><h2 className="mt-6 text-3xl font-bold">다음 단계 진행 승인이 완료됐습니다.</h2><button onClick={download} className="mt-8 rounded-2xl bg-[#191f28] px-7 py-4 font-bold text-white">승인 기록 내려받기</button></section>:<section className="mt-10 rounded-[28px] bg-white p-7 sm:p-10"><span className="rounded-full bg-[#e8f3ff] px-3 py-1 text-xs font-bold text-[#1b64da]">진행 순서 조정</span><h2 className="mt-5 text-2xl font-bold">제목·초록 선별을 먼저 진행합니다</h2><p className="mt-4 leading-7 text-[#4e5968]">19,619개 전체 보고서를 먼저 연구 단위로 연결하면 불필요한 작업이 큽니다. 제목·초록에서 관련 후보를 좁힌 뒤, 남은 보고서만 연구 단위로 연결하도록 순서를 조정합니다.</p><div className="mt-6 space-y-2">{["원본 레코드와 중복 판정은 그대로 보존", "선별 제외 사유와 판정 이력 기록", "포함 후보에 대해서만 연구 단위 연결"].map(x=><div key={x} className="rounded-2xl bg-[#f9fafb] p-4 font-semibold">✓ {x}</div>)}</div><button onClick={approve} className="mt-8 w-full rounded-2xl bg-[#3182f6] px-7 py-4 font-bold text-white">이 순서로 승인하고 진행</button></section>}</div></main>;
}
