"use client";
import {FormEvent,useRef,useState} from "react";

type Result={question_id:string;ingredient:string;title:string;summary:string;ai_summary:string;profile:string[];checks:string[];why:string;next_steps:string[];evidence:Array<{title:string;url:string;doi:string;dose:string;outcome:string}>;interpretation:string};
function Chevron(){return <svg aria-hidden="true" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4"><path d="m5 7.5 5 5 5-5"/></svg>}
export function PersonalizedSafetyQuery(){
 const formRef=useRef<HTMLFormElement>(null);
 const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 const examples=[
  {title:"와파린 + 비타민 K",description:"INR 변동과 섭취량 변화 확인",ingredient:"비타민 K",dose:"100 mcg/day",medication:"와파린",condition:"항응고 치료 중",labs:"INR 3.1"},
  {title:"항응고제 + 오메가-3",description:"고용량·출혈 병력 확인",ingredient:"오메가-3",dose:"EPA+DHA 2000 mg/day",medication:"아픽사반",condition:"코피가 자주 남",labs:""},
  {title:"결석 병력 + 칼슘",description:"식이량과 보충제 용량 구분",ingredient:"칼슘",dose:"600 mg/day",medication:"",condition:"칼슘옥살산 신장결석 병력",labs:"24시간 요중 칼슘 280 mg/day"},
  {title:"결석 병력 + 비타민 D",description:"혈청·요중 칼슘 확인",ingredient:"비타민 D",dose:"4000 IU/day",medication:"",condition:"신장결석 및 고칼슘뇨",labs:"25(OH)D 48 ng/mL"},
  {title:"고옥살산뇨 + 비타민 C",description:"고용량 노출과 옥살산 확인",ingredient:"비타민 C",dose:"1000 mg/day",medication:"",condition:"고옥살산뇨 및 결석 병력",labs:"요중 옥살산 상승"},
 ];
 function fillExample(x:typeof examples[number]){const f=formRef.current;if(!f)return;for(const [k,v] of Object.entries(x)){const el=f.elements.namedItem(k);if(el instanceof HTMLInputElement||el instanceof HTMLSelectElement)el.value=v}f.scrollIntoView({behavior:"smooth",block:"center"});setResult(null);setError("")}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch("/api/personalized-safety",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const body=await res.json();setLoading(false);if(!res.ok){setError(body.error??"조회할 수 없습니다.");setResult(null);return}setResult(body)}
 return <section className="mx-auto px-4 py-5 sm:px-5 sm:py-6" id="query">
  <div className="max-w-3xl"><p className="text-xs font-semibold text-muted">개인 특성 기반 안전성 조회</p><h2 className="mt-2 text-xl font-semibold tracking-[-0.025em]">복용 조건을 입력하세요</h2><p className="mt-2 text-sm leading-6 text-muted">성분, 용량, 약물, 질환과 검사값을 함께 조회합니다.</p></div>
  <details className="mt-5 overflow-hidden rounded-2xl border border-stone-200 bg-stone-50/70">
   <summary className="flex min-h-12 list-none items-center justify-between gap-4 px-4 py-3 text-left hover:bg-white/60"><div><span className="text-sm font-bold text-stone-900">예시 입력으로 바로 보기</span><span className="ml-2 text-xs text-stone-500">입력 없이 5개 상황 체험</span></div><span className="collapsible-chevron flex h-7 w-7 items-center justify-center rounded-full border border-stone-200 bg-white text-stone-600"><Chevron/></span></summary>
   <div className="collapsible-panel"><div className="collapsible-panel-inner"><div className="collapsible-panel-body border-t border-stone-200 p-3"><p className="mb-3 text-xs text-stone-500">예시를 누르면 아래 입력값이 자동으로 채워집니다.</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{examples.map(x=><button type="button" key={x.title} onClick={()=>fillExample(x)} className="rounded-xl border border-stone-200 bg-white p-3 text-left transition hover:border-blue-300 hover:shadow-sm"><span className="block text-sm font-bold text-stone-950">{x.title}</span><span className="mt-1 block text-xs leading-5 text-stone-600">{x.description}</span></button>)}</div></div></div></div>
  </details>
  <form ref={formRef} onSubmit={submit} className="mt-6 grid gap-5 rounded-3xl border border-stone-200 bg-white p-6 shadow-sm sm:grid-cols-2 sm:p-8">
   <label className="grid gap-2 text-sm font-semibold">보충제<select required name="ingredient" className="rounded-xl border border-stone-300 bg-white px-4 py-3"><option value="">선택</option><option>비타민 K</option><option>오메가-3</option><option>칼슘</option><option>비타민 D</option><option>비타민 C</option></select></label>
   <label className="grid gap-2 text-sm font-semibold">일일 복용량<input name="dose" placeholder="예: 1000 mg/day" className="rounded-xl border border-stone-300 px-4 py-3"/></label>
   <label className="grid gap-2 text-sm font-semibold">병용 약물<input name="medication" placeholder="예: 와파린" className="rounded-xl border border-stone-300 px-4 py-3"/></label>
   <label className="grid gap-2 text-sm font-semibold">질환·병력<input name="condition" placeholder="예: 신장결석, 고칼슘뇨" className="rounded-xl border border-stone-300 px-4 py-3"/></label>
   <label className="grid gap-2 text-sm font-semibold sm:col-span-2">관련 검사값<input name="labs" placeholder="예: INR 3.1, 혈청 칼슘 10.4 mg/dL" className="rounded-xl border border-stone-300 px-4 py-3"/></label>
   <button disabled={loading} className="min-h-12 rounded-xl bg-stone-950 px-5 font-semibold text-white sm:col-span-2">{loading?"근거를 조회하는 중":"근거와 확인사항 조회"}</button>
  </form>
  <aside className="mt-6 grid gap-4 rounded-2xl bg-blue-50 p-5 text-sm text-blue-950 sm:grid-cols-3"><div><strong className="block">1. 예시 선택</strong><span className="mt-1 block leading-6">대표 상황을 눌러 자동 입력합니다.</span></div><div><strong className="block">2. 값 변경</strong><span className="mt-1 block leading-6">용량·약물·검사값을 바꿔 결과를 비교합니다.</span></div><div><strong className="block">3. 근거 확인</strong><span className="mt-1 block leading-6">확인사항, 보고 용량, 원문 링크를 확인합니다.</span></div></aside>
  {error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
  {result&&<article className="mt-6 overflow-hidden rounded-2xl border border-stone-200 bg-white"><header className="bg-stone-950 px-5 py-5 text-white"><p className="text-xs font-semibold text-blue-200">한눈에 보는 결과</p><h3 className="mt-2 text-xl font-bold leading-7">{result.title}</h3></header><div className="p-5"><p className="rounded-2xl bg-blue-50 px-5 py-4 text-[15px] font-medium leading-7 text-stone-900">{result.ai_summary}</p><div className="mt-4 flex flex-wrap gap-2">{result.profile.map(x=><span key={x} className="rounded-full bg-stone-100 px-3 py-1.5 text-xs font-semibold text-stone-700">{x}</span>)}</div><details className="mt-5 rounded-xl border border-stone-200"><summary className="flex min-h-12 list-none items-center justify-between px-4 py-3 font-semibold"><span>확인할 내용과 다음 단계</span><span className="collapsible-chevron text-stone-500"><Chevron/></span></summary><div className="grid gap-5 border-t border-stone-200 p-4 md:grid-cols-2"><ol className="grid gap-2">{result.checks.map((x,i)=><li key={x} className="flex gap-3 text-sm leading-6"><b className="text-blue-700">{i+1}</b><span>{x}</span></li>)}</ol><ul className="grid gap-2 text-sm leading-6">{result.next_steps.map(x=><li key={x} className="flex gap-2"><span className="text-emerald-600">✓</span><span>{x}</span></li>)}</ul></div></details><details className="mt-3 rounded-xl border border-stone-200"><summary className="flex min-h-12 list-none items-center justify-between px-4 py-3 font-semibold"><span>논문과 세부 근거 보기</span><span className="flex items-center gap-2 text-sm text-stone-500">{result.evidence.length}건 <span className="collapsible-chevron"><Chevron/></span></span></summary><div className="divide-y divide-stone-200 border-t border-stone-200 px-4">{result.evidence.map((x,i)=><div key={i} className="py-4"><a href={x.url} target="_blank" rel="noreferrer" className="text-sm font-semibold text-blue-700 underline underline-offset-4">{x.title}</a>{x.dose&&<p className="mt-2 text-xs text-stone-600">문헌 보고 용량: {x.dose}</p>}</div>)}</div></details><p className="mt-4 text-xs leading-5 text-stone-500">{result.interpretation}</p></div></article>}
 </section>
}
