import {createHash} from "node:crypto";import {readFileSync,writeFileSync} from "node:fs";import path from "node:path";
import {runAiExploratoryEngine} from "../src/engine/run-ai-exploratory-engine";
const root=process.cwd(),sha=(v:string|Buffer)=>createHash("sha256").update(v).digest("hex"),fileSha=(p:string)=>sha(readFileSync(path.join(root,p)));
const scenarios=readFileSync(path.join(root,"research/validation/synthetic_scenario_inputs.jsonl"),"utf8").trim().split(/\r?\n/).map(x=>JSON.parse(x));
let deterministic=0,correctRoute=0,clinicalLeak=0,legacyLeak=0,provenanceComplete=0;const results=[];
for(const s of scenarios){const outputs=Array.from({length:3},()=>runAiExploratoryEngine(s.input));const serial=outputs.map(output=>JSON.stringify(output)),same=serial.every(x=>x===serial[0]);if(same)deterministic++;const out=outputs[0];if(out.navigation.length===1&&out.navigation[0].question_id===s.question_id)correctRoute++;if(out.clinical_actions.length||/urgent_referral|avoid_until_review|pharmacist_review/.test(serial[0]))clinicalLeak++;if(/legacy_unverified|RULE-VIT/.test(serial[0]))legacyLeak++;if(out.navigation.every(n=>/^[a-f0-9]{64}$/.test(n.support.sha256)&&/^[a-f0-9]{64}$/.test(n.support.manifest_sha256)))provenanceComplete++;results.push({scenario_id:s.scenario_id,question_id:s.question_id,input_sha256:s.input_sha256,output_sha256:sha(serial[0]),deterministic:same,routed_question_ids:out.navigation.map(n=>n.question_id)});}
const negatives=["vitamin","K vitamin","omega","fish","calc","D vitamin","ascorb","warfarin"].map(name=>runAiExploratoryEngine({profile:{},candidateItems:[{name}]}));const negativeFalseRoutes=negatives.filter(x=>x.navigation.length).length;
const report={schema_version:"1.0.0",protocol_version:"2.0-ai-exploratory",status:"synthetic_technical_validation_not_independent_gold",clinical_performance_claim_allowed:false,scenario_count:scenarios.length,repeats_per_scenario:3,executions:scenarios.length*3,deterministic_scenarios:deterministic,correct_exact_route_scenarios:correctRoute,provenance_complete_scenarios:provenanceComplete,clinical_action_leakage_scenarios:clinicalLeak,legacy_leakage_scenarios:legacyLeak,negative_near_match_cases:negatives.length,negative_false_routes:negativeFalseRoutes,independent_gold_scenarios:0,source_hashes:{runner:fileSha("scripts/evaluate-ai-exploratory-scenarios.ts"),engine:fileSha("src/engine/run-ai-exploratory-engine.ts"),bundle:fileSha("src/generated/ai-exploratory-bundle.json"),inputs:fileSha("research/validation/synthetic_scenario_inputs.jsonl")},scenarios:results};
writeFileSync(path.join(root,"research/validation/ai_exploratory_performance.json"),JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({scenarios:report.scenario_count,deterministic,correctRoute,provenanceComplete,clinicalLeak,legacyLeak,negativeFalseRoutes}));if([deterministic,correctRoute,provenanceComplete].some(x=>x!==120)||clinicalLeak||legacyLeak||negativeFalseRoutes)process.exit(1);
